[package]
name = "fisher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blowfish = "0.9.1"
rpassword = "7.3.1"
sha2 = "0.10.8"
threefish = "0.5.2"
twofish = "0.7.1"
